config/routes.rb
DineroMailFakeIpn::Application.routes.draw do
  resources :integration_requests, only: :create do
    resource :operation, only: [:new, :create]
  end

  resources :queries, only: :create

end

app/models/answerer.rb
class Answerer
  attr_reader :query

  def initialize(query)
    @query = query
  end

  def answer_document
    builder = Nokogiri::XML::Builder.new do |xml|
      xml.REPORTE {
        xml.ESTADOREPORTE status
          xml.DETALLE {
            xml.OPERACIONES { transactions.each { |transaction|
              xml.OPERACION {
                xml.ID  transaction.client_id
                xml.FECHA transaction.created_at.strftime('%d/%m/%Y %I:%M:%S %p')
                xml.ESTADO transaction.status
                xml.NUMTRANSACCION transaction.id
                xml.COMPRADOR {
                  xml.EMAIL transaction.buyer_email
                  xml.DIRECCION transaction.buyer_address
                  xml.COMENTARIO transaction.buyer_comment
                  xml.NOMBRE transaction.buyer_full_name
                  xml.TELEFONO transaction.buyer_phone
                  xml.TIPODOC transaction.buyer_document_type.upcase
                  xml.NUMERODOC transaction.buyer_document_number }
                xml.MONTO format_amount(transaction.amount)
                xml.MONTONETO format_amount(transaction.net_amount)
                xml.METODOPAGO transaction.payment_method_type
                xml.MEDIOPAGO transaction.payment_method
                xml.CUOTAS transaction.number_of_payments
                xml.ITEMS { transaction.items.each { |item|
                  xml.ITEM {
                    xml.DESCRIPCION item.name
                    xml.MONEDA '1' # TODO
                    xml.PRECIOUNITARIO format_amount(item.amount)
                    xml.CANTIDAD item.quantity }}}
                xml.VENDEDOR
                  # TODO stop faking it.
                  xml.TIPODOC 'DNI'
                  xml.NUMERODOC '12345678' }}}}}
    end
    builder.to_xml
  end

private

  def status
    transactions.empty? ? '8' : '1'
  end

  def transactions
    @transactions ||= Operation.query(query.transaction_ids)
  end

  def format_amount(amount)
    amount.to_s(:rounded, precision: 2, separator: '.')
  end
end

app/models/integration_request.rb
class IntegrationRequest < ActiveRecord::Base
  has_one :operation

  serialize :raw

  def build_operation(attributes = {})
    super(attributes.merge(unchangeable_operation_attributes))
  end

  def build_prefilled_operation
    build_operation(prefilled_operation_attributes)
  end

  def ok_url
    raw['ok_url']
  end

private

  def unchangeable_operation_attributes
    {
      client_id: raw['transaction_id'],
      items: items_attributes.map { |item_attributes| Item.new(item_attributes) }
    }
  end

  def prefilled_operation_attributes
    {
      buyer_phone: raw['buyer_phone'],
      buyer_email: raw['buyer_email']
    }
  end

  def items_attributes
    result = []
    raw.each do |key, value|
      if (match = key.match(/item_(name|ammount|quantity)_(\d+)/))
        index = match.captures[1].to_i - 1
        name = match.captures[0]
        if name == 'ammount'
          name = 'amount'
          value = value.to_i / 100.0
        end
        (result[index] ||= {})[name] = value
      end
    end
    result
  end
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :operation

  def subtotal
    amount * quantity
  end
end

app/models/notification.rb
class Notification
  def initialize(operation_client_ids)
    @operation_client_ids = operation_client_ids
  end

  def document
    builder = Nokogiri::XML::Builder.new do |xml|
      xml.notificacion {
        xml.tiponotificacion 1
        xml.operaciones { @operation_client_ids.each { |id|
          xml.operacion {
            xml.tipo 1
            xml.id id }}}}
    end
    builder.to_xml
  end
end

app/models/operation.rb
class Operation < ActiveRecord::Base
  belongs_to :integration_request
  has_many :items
  has_many :transitions

  accepts_nested_attributes_for :transitions

  def self.query(ids)
    where(client_id: ids)
  end

  def net_amount
    items.map(&:subtotal).sum
  end

  def amount
    net_amount * BigDecimal('1.06')
  end
end

app/models/query.rb
class Query < ActiveRecord::Base
  class CantBeAnsweredError < StandardError; end

  def transaction_ids
    find_transaction_ids_in_question_hash
  end

  def answer
    raise CantBeAnsweredError if question_document.blank?
    answerer = Answerer.new(self)
    self.answer_document = answerer.answer_document
  end

private

  def find_transaction_ids_in_question_hash
    # TODO: understand how Nori works, think if is worth failing louder when the
    # question document is invalid, replace Nori, I don't really know right now.
    # What I do know is that this is ugly.
    Array(question_hash['reporte']['detalle']['consulta']['operaciones']['id'])
  rescue NoMethodError
    []
  end

  def question_hash
    parser = Nori.new(convert_tags_to: ->(tag){ tag.downcase })
    parser.parse(question_document)
  end
end

app/models/transition.rb
class Transition < ActiveRecord::Base
  belongs_to :operation

  validates :schedule_delay, numericality: { only_integer: true, greater_than_or_equal_to: 0 }, if: :new_record?

  before_create :set_scheduled_at

  attr_accessor :schedule_delay

  def self.ready(comparison_time = Time.now)
    where(performed_at: nil).where(arel_table[:scheduled_at].lteq(comparison_time))
  end

  def ready?(comparison_time = current_time_from_proper_timezone)
    !performed? and on_schedule?(comparison_time)
  end

  def on_schedule?(comparison_time = current_time_from_proper_timezone)
    scheduled_at <= comparison_time
  end

  def performed?
    performed_at.present?
  end

  def perform
    raise TransitionError if performed? or !on_schedule?

    transaction do
      operation.update_attributes!(status: status)
      update_attributes!(performed_at: current_time_from_proper_timezone)
    end
  end

private

  def set_scheduled_at
    self.scheduled_at = created_at + schedule_delay.to_i.minutes
  end
end

class TransitionError < StandardError; end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/integration_requests_controller.rb
class IntegrationRequestsController < ApplicationController
  skip_before_filter :verify_authenticity_token

  def create
    @integration_request = IntegrationRequest.create!(integration_request_attributes)
    redirect_to new_integration_request_operation_url(@integration_request)
  end

private

  def integration_request_attributes
    { raw: params.except(*request.path_parameters.keys) }
  end
end

app/controllers/operations_controller.rb
class OperationsController < ApplicationController
  before_filter :find_integration_request

  def new
    @operation = @integration_request.build_prefilled_operation
    5.times { @operation.transitions.build }
  end

  def create
    @operation = @integration_request.build_operation(operation_params)

    if @operation.save
      redirect_to @integration_request.ok_url
    else
      render :new
    end
  end

private

  def find_integration_request
    @integration_request = IntegrationRequest.find(params[:integration_request_id])
  end

  def operation_params
    params.require(:operation).permit(:buyer_full_name, :buyer_document_type, :buyer_document_number, :buyer_email, :buyer_address, :buyer_comment, :buyer_phone, :payment_method_type, :payment_method, :number_of_payments, transitions_attributes: [:status, :schedule_delay, :needs_notification])
  end
end

app/controllers/queries_controller.rb
class QueriesController < ApplicationController
  skip_before_filter :verify_authenticity_token

  def create
    query = Query.new(question_document: params[:DATA])
    query.answer
    query.save!

    send_data(query.answer_document, type: 'application/xml')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/operations_helper.rb
# encoding: utf-8
module OperationsHelper
  def buyer_document_types_collection
    [['D.N.I.', 'dni']]
  end

  def payment_method_types_collection
    [['Tarjeta de Crédito', 3]]
  end

  def payment_methods_collection
    [['Visa', 'VISA']]
  end

  def number_of_payments_collection
    [0]
  end

  def statuses_collection
    [['Pendiente De Pago', 1], ['Acreditado', 2], ['Cancelado', 3]]
  end

  def schedule_delays_collection
    [['No Esperar', 0], ['1 Minuto', 1], ['5 Minutos', 5], ['15 Minutos', 15]]
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DineroMailFakeIpn</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="container">
    <%= yield %>
  </div>

</body>
</html>

app/views/operations/_form.html.erb
<%= form_for(@operation, url: integration_request_operation_path(@integration_request), html: { class: 'form-horizontal' }) do |f| %>
  <fieldset>
    <legend>Información del comprador</legend>
    <div class="control-group">
      <%= f.label :buyer_full_name, class: 'control-label' %>
      <div class="controls">
        <%= f.text_field :buyer_full_name %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :buyer_document_type, class: 'control-label' %>
      <div class="controls">
        <%= f.select :buyer_document_type, buyer_document_types_collection %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :buyer_document_number, class: 'control-label' %>
      <div class="controls">
        <%= f.text_field :buyer_document_number %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :buyer_email, class: 'control-label' %>
      <div class="controls">
        <%= f.text_field :buyer_email %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :buyer_address, class: 'control-label' %>
      <div class="controls">
        <%= f.text_field :buyer_address %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :buyer_phone, class: 'control-label' %>
      <div class="controls">
        <%= f.text_field :buyer_phone %>
      </div>
    </div>
  </fieldset>

  <fieldset>
    <legend>Información del Pago</legend>
    <div class="control-group">
      <%= f.label :payment_method_type, class: 'control-label' %>
      <div class="controls">
        <%= f.select :payment_method_type, payment_method_types_collection %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :payment_method, class: 'control-label' %>
      <div class="controls">
        <%= f.select :payment_method, payment_methods_collection %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :number_of_payments, class: 'control-label' %>
      <div class="controls">
        <%= f.select :number_of_payments, number_of_payments_collection %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :buyer_comment, class: 'control-label' %>
      <div class="controls">
         <%= f.text_area :buyer_comment, rows: 5 %>
      </div>
    </div>
  </fieldset>

  <fieldset>
    <legend>Transiciones</legend>
    <table class="table">
      <thead>
        <tr>
          <th></th>
          <th>Estado</th>
          <th>Demorar</th>
          <th>Notificar</th>
        </tr>
      </thead>
      <tbody>
        <%= f.fields_for :transitions do |transition_fields| %>
          <tr>
            <td><span class="badge"><%= transition_fields.index + 1 %></span></td>
            <td><%= transition_fields.select :status, statuses_collection %></td>
            <td><%= transition_fields.select :schedule_delay, schedule_delays_collection %></td>
            <td><%= transition_fields.check_box :needs_notification %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <div class="transition_actions">
      <a class="btn btn-mini btn-success add_transition" href="#"><i class="icon-plus icon-white"></i></a>
      <a class="btn btn-mini btn-danger remove_transition" href="#"><i class="icon-minus icon-white"></i></a>
    </div>
  </fieldset>

  <fieldset>
    <div class="form-actions">
      <%= f.submit class: 'btn btn-primary' %>
    </div>
  </fieldset>
<% end %>

app/views/operations/new.html.erb
<div class="page-header">
  <h1>Simular transacción en Dinero Mail</h1>
</div>

<%= render 'form' %>